import Link from "next/link";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="page">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
